Docs/post implementation updates
hyperledger/indy-did-method pull request #65
Opened 2022-04-09 00:40 UTC by cjhowland

This PR updates the Indy DID Method Specification based on implementation. In particular, it adds details about `DIDDoc` and `diddocContent` validation, ensuring NYM transaction `version` is not updated on existing NYMs, and legacy support for resolving ATTRIBs by a previous version.

2022-04-11 14:21 UTC, dbluhm requested changes
Spotted what I think is a typo :slightly_smiling_face:

2022-04-11 14:21 UTC, dbluhm commented on spec/3_indy_ledger_object_glossary.md
> +~ The `did:indy` method introduces legacy support for retrieving the service endpoint of a past version of a [[ref: NYM]] by `versionId` or `versionTime`, using a process similar to resolving [DID Ve
```suggestion
~ The `did:indy` method introduces legacy support for retrieving the service endpoint of a past version of an attribute by `versionId` or `versionTime`, using a process similar to resolving [DID Versions](\https://hyperledger.github.io/indy-did-method/#did-versions) by these parameters.
```

I believe this is what was intended?

2022-04-11 18:50 UTC, dbluhm submitted a review, later dismissed

2022-04-11 20:26 UTC, swcurran commented on spec/3_indy_ledger_object_glossary.md
> +credential validation and can be [read](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/requests.html#get-claim-def) by any Hyperledger Indy client. A CLAIM_DEF object references a [[
I think we should update this to use "CRED_DEF" with a note that "CLAIM_DEF" is sometimes used, particularly in existing Hyperledger Indy code.

It would be nice to keep stamping out the use of "CLAIM_DEF".

2022-04-11 20:26 UTC, swcurran commented on spec/3_indy_ledger_object_glossary.md
> +credential validation and can be [read](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/requests.html#get-claim-def) by any Hyperledger Indy client. A CLAIM_DEF object references a [[
We could include a "CLAIM_DEF" definition, but just say it is the deprecated term for "CRED_DEF".

2022-04-11 20:27 UTC, swcurran commented on spec/3_indy_ledger_object_glossary.md
> +~ A NYM object itself does not conform to the [Decentralized Identifiers (DIDs) Core specification](https://https://www.w3.org/TR/did-core/) scheme but rather includes all DID related data of a singl
Missing an "and" in the last sentence, I think.

2022-04-11 20:28 UTC, swcurran commented
Looks good -- a couple of minor tweaks suggested.

2022-04-12 14:05 UTC, swcurran approved these changes

2022-04-12 14:05 UTC, merged